version: "3.5"

networks:
  internet:
    name: internet
    driver: bridge
  appnet:
    name: appnet
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: lukesv/livestock-postgres
    networks:
      - appnet
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    
  liquibase:
    container_name: liquibase
    image: lukesv/livestock-liquibase
    networks:
      - appnet
    restart: on-failure
    depends_on:
      - postgres
      
  discovery-server:
    container_name: discovery-server
    image: lukesv/livestock-discovery-server
    networks:
      - appnet
    ports:
      - "8761:8761"
    environment:
      SERVER_HOSTNAME: discovery-server
      SERVER_PORT: 8761
    restart: unless-stopped